#!/usr/bin/env python3
"""Full measured-auction portfolio, with NautilusTrader as sole engine.

This candidate combines three mutually exclusive responses:

1. A failed sweep aligned with 160-bps outer structure and opposite-flow
   takeover rotates to the nearest still-open opposing pivot.
2. A countertrend failed-sweep reversal which itself fails expands one accepted
   outside-excursion width beyond the failed-reversal path extreme.
3. A directional-change pivot which retained outside value and held its old
   boundary projects the accepted boundary-to-extreme range once beyond that
   extreme.

For measured expansions, structural invalidation is one economically derived
26-bps price-risk unit through the active acceptance boundary.  No target or
stop is selected from strategy PnL.  All fills, costs, margin and NAV are
exclusively generated by NautilusTrader on official Binance one-minute bars.
"""
from __future__ import annotations

import argparse
from collections import Counter
from dataclasses import asdict
from datetime import timedelta
import json
from pathlib import Path
import sys
from typing import Any

import pandas as pd

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
SRC = ROOT / "src"
for item in (HERE, SRC):
    if str(item) not in sys.path:
        sys.path.insert(0, str(item))

from adaptive_aggtrade_clock import build_daily_cost_resolved_bars  # noqa: E402
from aggtrade_data import download_aggtrade_days  # noqa: E402
from core import Side  # noqa: E402
from data import load_interval, parse_utc_date  # noqa: E402
from directional_change_failed_sweep_week import (  # noqa: E402
    MAXIMUM_HOLD_NS,
    MINIMUM_COST_RESOLVABLE_RISK_BPS,
)
from impact_regime_probe import ImpactRegimeDetector, ScenarioPlan  # noqa: E402
from intrinsic_external_liquidity_v2_daily_week import (  # noqa: E402
    CLOCK_SOURCE_EXTRA_DAYS,
    DAILY_CANDIDATE_MINUTES,
    ROUND_TRIP_COST_BPS,
)
from intrinsic_external_liquidity_v2_week import (  # noqa: E402
    CONTEXT_WARMUP_DAYS,
    NS_PER_HOUR,
    TargetFreeSweepRetestDetector,
    outer_state_series,
)
from intrinsic_external_liquidity_v3_router import build_open_liquidity_snapshots  # noqa: E402
from intrinsic_failed_reversal_continuation_v8_nautilus_week import (  # noqa: E402
    build_aligned_reversal_plans,
    build_confirmations,
)
from intrinsic_measured_acceptance_v10_nautilus_week import measured_plans  # noqa: E402
from intrinsic_outside_acceptance_v9_nautilus_week import (  # noqa: E402
    OutsideValueAcceptanceDetector,
)
from nautilus_plan_backtest import (  # noqa: E402
    NautilusExecutionConfig,
    run_nautilus_plan_backtest,
)

RULES = ("direct-measured-only", "full-measured-composite")
PRICE_RISK_FRACTION = MINIMUM_COST_RESOLVABLE_RISK_BPS / 10_000.0


def atomic_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    temporary.replace(path)


def load_execution(path: Path) -> NautilusExecutionConfig:
    config = NautilusExecutionConfig.from_mapping(
        json.loads(path.read_text(encoding="utf-8")),
    )
    if abs(config.risk_fraction - 0.03) > 1e-12:
        raise ValueError("authoritative candidate-01 evaluations require 3% risk")
    return config


def direct_measured_plans(
    signals: list[Any],
    features: list[Any],
    outer_states: list[str],
) -> tuple[list[ScenarioPlan], list[dict[str, Any]]]:
    plans: list[ScenarioPlan] = []
    decisions: list[dict[str, Any]] = []
    for signal in signals:
        state = outer_states[signal.signal_bar_index]
        aligned = (
            (signal.side is Side.LONG and state == "BULL")
            or (signal.side is Side.SHORT and state == "BEAR")
        )
        if not aligned:
            decisions.append(
                {
                    "scenario_id": signal.scenario_id,
                    "signal_time_ns": signal.signal_time_ns,
                    "side": signal.side.value,
                    "outer_state": state,
                    "routed": False,
                    "reason_code": "OUTSIDE_VALUE_NOT_ALIGNED_WITH_OUTER_STRUCTURE",
                },
            )
            continue

        if signal.side is Side.LONG:
            accepted_width = signal.path_high - signal.boundary
            stop = signal.boundary * (1.0 - PRICE_RISK_FRACTION)
            target = signal.path_high + accepted_width
            geometry = stop < features[signal.signal_bar_index].bar.close < target
        else:
            accepted_width = signal.boundary - signal.path_low
            stop = signal.boundary * (1.0 + PRICE_RISK_FRACTION)
            target = signal.path_low - accepted_width
            geometry = target < features[signal.signal_bar_index].bar.close < stop
        if accepted_width <= 0.0:
            reason = "ZERO_ACCEPTED_OUTSIDE_RANGE"
        elif not geometry:
            reason = "INVALID_DIRECT_MEASURED_GEOMETRY"
        else:
            plan = ScenarioPlan(
                scenario_id=(
                    f"direct-measured-acceptance:{signal.signal_bar_index}:"
                    f"{signal.side.value.lower()}:{signal.signal_time_ns}"
                ),
                response="DIRECT_OUTSIDE_VALUE_MEASURED_CONTINUATION",
                side=signal.side,
                signal_bar_index=signal.signal_bar_index,
                signal_time_ns=signal.signal_time_ns,
                stop_price=stop,
                target_price=target,
                confirmation_hold_price=signal.boundary,
                structure_high=max(signal.path_high, stop, target),
                structure_low=min(signal.path_low, stop, target),
                structure_midpoint=0.5 * (signal.boundary + target),
                pulse_high=signal.path_high,
                pulse_low=signal.path_low,
                pulse_flow_score=signal.reversal_flow_imbalance,
                pulse_move_atr=0.0,
                pulse_path_efficiency=0.0,
                pulse_close_location=0.0,
                reason_code="OUTSIDE_VALUE_ACCEPTED_RANGE_MEASURED_EXPANSION",
            )
            plans.append(plan)
            decisions.append(
                {
                    "scenario_id": signal.scenario_id,
                    "signal_time_ns": signal.signal_time_ns,
                    "side": signal.side.value,
                    "outer_state": state,
                    "routed": True,
                    "reason_code": plan.reason_code,
                    "accepted_width": accepted_width,
                    "selected_stop": stop,
                    "selected_target": target,
                },
            )
            continue
        decisions.append(
            {
                "scenario_id": signal.scenario_id,
                "signal_time_ns": signal.signal_time_ns,
                "side": signal.side.value,
                "outer_state": state,
                "routed": False,
                "reason_code": reason,
            },
        )
    return plans, decisions


def run(args: argparse.Namespace) -> int:
    execution = load_execution(args.execution_config)
    evaluation_start = parse_utc_date(args.week)
    evaluation_end = evaluation_start + timedelta(days=7)
    context_start = evaluation_start - timedelta(days=CONTEXT_WARMUP_DAYS)
    clock_source_start = context_start - timedelta(days=CLOCK_SOURCE_EXTRA_DAYS)
    start_ns = int(pd.Timestamp(evaluation_start).as_unit("ns").value)
    end_ns = int(pd.Timestamp(evaluation_end).as_unit("ns").value)

    signal_records = download_aggtrade_days(
        symbol="BTCUSDT",
        start=clock_source_start,
        end=evaluation_end,
        cache_dir=args.cache,
        workers=args.workers,
    )
    bars, calibrations = build_daily_cost_resolved_bars(
        signal_records,
        bar_start=context_start,
        bar_end=evaluation_end,
        minimum_range_bps=ROUND_TRIP_COST_BPS,
        candidate_minutes=DAILY_CANDIDATE_MINUTES,
    )
    execution_frame, execution_records = load_interval(
        symbol="BTCUSDT",
        start=evaluation_start,
        end=evaluation_end,
        cache_dir=args.cache / "execution-klines",
        warmup_minutes=2,
    )

    feature_detector = ImpactRegimeDetector()
    failed_detector = TargetFreeSweepRetestDetector()
    acceptance_detector = OutsideValueAcceptanceDetector()
    for bar in bars:
        feature_detector.on_bar(bar)
        index = len(feature_detector.features) - 1
        failed_detector.on_feature(index=index, features=feature_detector.features)
        acceptance_detector.on_feature(index=index, features=feature_detector.features)
    features = feature_detector.features
    outer_states = outer_state_series(features)
    failed_signals = [
        signal for signal in failed_detector.signals
        if start_ns <= signal.signal_time_ns < end_ns
    ]
    acceptance_signals = [
        signal for signal in acceptance_detector.signals
        if start_ns <= signal.signal_time_ns < end_ns
    ]
    cost = execution.all_in_cost_bps_per_side / 10_000.0
    failed_snapshots = build_open_liquidity_snapshots(
        features=features,
        events=failed_detector.detector.events,
        signal_indices=(signal.signal_bar_index for signal in failed_signals),
    )

    direct_plans, direct_decisions = direct_measured_plans(
        acceptance_signals,
        features,
        outer_states,
    )
    reversal_plans: list[ScenarioPlan] = []
    failed_measured_plans: list[ScenarioPlan] = []
    failed_measured_decisions: list[dict[str, Any]] = []
    reversal_decisions: list[dict[str, Any]] = []
    confirmations: list[Any] = []

    if args.rule == "full-measured-composite":
        reversal_plans, reversal_decisions = build_aligned_reversal_plans(
            signals=failed_signals,
            features=features,
            outer_states=outer_states,
            events=failed_detector.detector.events,
            snapshots=failed_snapshots,
            cost=cost,
            minimum_price_risk_fraction=execution.minimum_price_risk_fraction,
            minimum_net_reward_risk=execution.minimum_net_reward_risk,
        )
        confirmations, _ = build_confirmations(
            signals=failed_signals,
            features=features,
            outer_states=outer_states,
            events=failed_detector.detector.events,
            signal_snapshots=failed_snapshots,
            cost=cost,
            minimum_price_risk_fraction=execution.minimum_price_risk_fraction,
            minimum_net_reward_risk=execution.minimum_net_reward_risk,
            evaluation_end_ns=end_ns,
        )
        failed_measured_plans, failed_measured_decisions = measured_plans(
            confirmations,
            features,
        )

    plans = list(direct_plans)
    if args.rule == "full-measured-composite":
        plans.extend(reversal_plans)
        plans.extend(failed_measured_plans)

    output = args.output
    output.mkdir(parents=True, exist_ok=True)
    evidence = run_nautilus_plan_backtest(
        label=f"BTCUSDT-{args.rule}-{evaluation_start.date().isoformat()}-7d",
        features=features,
        execution_frame=execution_frame,
        plans=plans,
        evaluation_start=evaluation_start,
        evaluation_end=evaluation_end,
        execution=execution,
        maximum_hold_ns=MAXIMUM_HOLD_NS,
        output_dir=output,
    )

    pd.DataFrame(asdict(row) for row in acceptance_signals).to_csv(
        output / "acceptance_signals.csv", index=False,
    )
    pd.DataFrame(direct_decisions).to_csv(output / "direct_measured_decisions.csv", index=False)
    pd.DataFrame(asdict(row) for row in confirmations).to_csv(
        output / "failed_reversal_confirmations.csv", index=False,
    )
    pd.DataFrame(failed_measured_decisions).to_csv(
        output / "failed_reversal_measured_decisions.csv", index=False,
    )
    pd.DataFrame(reversal_decisions).to_csv(output / "reversal_decisions.csv", index=False)
    pd.DataFrame(item.to_dict() for item in calibrations).to_json(
        output / "daily_clock_calibrations.json", orient="records", indent=2,
    )

    payload = {
        "candidate": "full measured intrinsic auction portfolio",
        "rule": args.rule,
        "authoritative_backtest": True,
        "execution_engine": "NautilusTrader",
        "custom_fill_simulator": False,
        "custom_pnl_or_nav_ledger": False,
        "execution_market_data": "official Binance Vision USD-M one-minute klines",
        "evaluation_start_utc": evaluation_start.isoformat(),
        "evaluation_end_utc": evaluation_end.isoformat(),
        "direct_acceptance_signals": len(acceptance_signals),
        "direct_measured_plans": len(direct_plans),
        "failed_reversal_confirmations": len(confirmations),
        "failed_reversal_measured_plans": len(failed_measured_plans),
        "aligned_flow_takeover_reversal_plans": len(reversal_plans),
        "submitted_plan_pool": len(plans),
        "direct_routing_counts": dict(Counter(row["reason_code"] for row in direct_decisions)),
        "failed_routing_counts": dict(Counter(row["reason_code"] for row in failed_measured_decisions)),
        "risk_fraction": execution.risk_fraction,
        "all_in_cost_bps_per_side": execution.all_in_cost_bps_per_side,
        "minimum_cost_resolvable_price_risk_bps": MINIMUM_COST_RESOLVABLE_RISK_BPS,
        "maximum_hold_hours": MAXIMUM_HOLD_NS / NS_PER_HOUR,
        "metrics": evidence.metrics,
        "signal_downloads": [record.to_dict() for record in signal_records],
        "execution_downloads": [asdict(record) for record in execution_records],
        "long_evaluation_run": False,
    }
    atomic_json(output / "intrinsic_full_measured_v11_summary.json", payload)
    print(json.dumps(payload, indent=2, sort_keys=True))
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--week", required=True)
    parser.add_argument("--rule", required=True, choices=RULES)
    parser.add_argument(
        "--execution-config", type=Path, default=HERE / "nautilus_execution.json",
    )
    parser.add_argument(
        "--cache", type=Path, default=ROOT / ".cache" / "candidate-01-v11-full-measured",
    )
    parser.add_argument(
        "--output", type=Path, default=ROOT / "artifacts" / "candidate-01-v11-full-measured",
    )
    parser.add_argument("--workers", type=int, default=4)
    return parser


if __name__ == "__main__":
    raise SystemExit(run(build_parser().parse_args()))
