#!/usr/bin/env python3
"""Aggregate Candidate 15 FAR execution development replays.

This is a diagnostic comparison over already-exposed development intervals.  It
never emits a success claim and cannot promote a strategy to validation.  All
PnL and NAV values are read from NautilusTrader evidence generated by the two
execution variants.
"""
from __future__ import annotations

import argparse
import csv
from collections import Counter, defaultdict
from decimal import Decimal
import json
import math
from pathlib import Path
from typing import Any

VARIANTS = ("SWEEP_MARKET", "PASSIVE_RETEST")
WEEKS = tuple(f"H{i:02d}" for i in range(1, 17))
DAYS = 112


def load(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def decimal(value: Any) -> Decimal:
    return Decimal(str(value))


def aggregate_variant(root: Path, variant: str) -> dict[str, Any]:
    nav_multiple = Decimal("1")
    trades = wins = losses = active = 0
    net_pnl = Decimal("0")
    positive_log: dict[str, float] = {}
    module_trades: Counter[str] = Counter()
    scenario_trades: Counter[str] = Counter()
    symbol_trades: Counter[str] = Counter()
    stop_models: Counter[str] = Counter()
    entry_models: Counter[str] = Counter()
    exit_reasons: Counter[str] = Counter()
    safety = True
    weeks: list[dict[str, Any]] = []

    for week in WEEKS:
        folder = root / variant / week
        metrics = load(folder / "metrics.json")
        audit = load(folder / "audit.json")
        plans = load(folder / "submitted_plans.json").get("plans", [])
        ratio = decimal(metrics["final_nav"]) / decimal(metrics["starting_nav"])
        nav_multiple *= ratio
        log_growth = math.log(float(ratio))
        if log_growth > 0:
            positive_log[week] = log_growth
        count = int(metrics.get("closed_trades", 0))
        trades += count
        wins += int(metrics.get("wins", 0))
        losses += int(metrics.get("losses", 0))
        active += int(count > 0)
        net_pnl += decimal(metrics.get("net_pnl", 0))
        safety_keys = (
            "evidence_complete",
            "metric_recalculation_passed",
            "risk_budget_passed",
            "global_slot_passed",
            "partial_entry_protection_passed",
            "no_liquidation_passed",
            "engine_errors_absent",
        )
        week_safety = all(audit.get(key) is True for key in safety_keys)
        safety = safety and week_safety
        for plan in plans:
            module_trades[str(plan.get("module", "UNKNOWN"))] += 1
            scenario_trades[str(plan.get("scenario", "UNKNOWN"))] += 1
            symbol_trades[str(plan.get("symbol", "UNKNOWN"))] += 1
            details = plan.get("details", {}) or {}
            stop_models[str(details.get("stop_model", "UNSPECIFIED"))] += 1
            entry_models[str(details.get("entry_model", "UNSPECIFIED"))] += 1
        positions_path = folder / "positions.csv"
        if positions_path.is_file():
            with positions_path.open(newline="", encoding="utf-8") as handle:
                for row in csv.DictReader(handle):
                    exit_reasons[str(row.get("exit_reason", "UNKNOWN"))] += 1
        weeks.append(
            {
                "week": week,
                "daily_geometric_growth": metrics.get("daily_geometric_growth"),
                "closed_trades": count,
                "wins": metrics.get("wins", 0),
                "losses": metrics.get("losses", 0),
                "nav_ratio": float(ratio),
                "final_nav": metrics.get("final_nav"),
                "safety": week_safety,
                "module_counts": metrics.get("module_counts", {}),
            }
        )

    daily = float(nav_multiple ** (Decimal("1") / Decimal(DAYS)) - Decimal("1"))
    positive_total = sum(positive_log.values())
    concentration = max(positive_log.values(), default=0.0) / positive_total if positive_total > 0 else 0.0
    avg_win = avg_loss = payoff = None
    pnl_by_outcome: defaultdict[str, list[float]] = defaultdict(list)
    for week in WEEKS:
        positions_path = root / variant / week / "positions.csv"
        if not positions_path.is_file():
            continue
        with positions_path.open(newline="", encoding="utf-8") as handle:
            for row in csv.DictReader(handle):
                raw = row.get("realized_pnl") or row.get("realized_pnl_event") or row.get("native_account_pnl")
                if raw is None:
                    continue
                text = str(raw).split()[0]
                pnl = float(text)
                pnl_by_outcome["win" if pnl > 0 else "loss" if pnl < 0 else "flat"].append(pnl)
    if pnl_by_outcome["win"]:
        avg_win = sum(pnl_by_outcome["win"]) / len(pnl_by_outcome["win"])
    if pnl_by_outcome["loss"]:
        avg_loss = abs(sum(pnl_by_outcome["loss"]) / len(pnl_by_outcome["loss"]))
    if avg_win is not None and avg_loss not in (None, 0.0):
        payoff = avg_win / avg_loss

    return {
        "variant": variant,
        "observed_calendar_days": DAYS,
        "nav_multiple": float(nav_multiple),
        "daily_geometric_growth": daily,
        "net_pnl": float(net_pnl),
        "closed_trades": trades,
        "wins": wins,
        "losses": losses,
        "win_rate": wins / trades if trades else 0.0,
        "active_weeks": active,
        "average_win": avg_win,
        "average_loss": avg_loss,
        "payoff_ratio": payoff,
        "positive_growth_concentration": concentration,
        "all_safety_audits": safety,
        "module_submitted_plans": dict(sorted(module_trades.items())),
        "scenario_submitted_plans": dict(sorted(scenario_trades.items())),
        "symbol_submitted_plans": dict(sorted(symbol_trades.items())),
        "entry_models": dict(sorted(entry_models.items())),
        "stop_models": dict(sorted(stop_models.items())),
        "exit_reasons": dict(sorted(exit_reasons.items())),
        "weeks": weeks,
        "success_claim": False,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, required=True)
    parser.add_argument("--baseline", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    baseline = load(args.baseline)
    variants = {variant: aggregate_variant(args.root, variant) for variant in VARIANTS}
    payload = {
        "schema": "candidate-15-far-execution-development-comparison-v1",
        "classification": "DEVELOPMENT_REPLAY_ONLY_NO_SUCCESS_CLAIM",
        "research_question": "Did Candidate 14 fail because FAR market reclassification and displacement-void invalidation chased confirmation or declared normal retest to be structural failure?",
        "invariants": [
            "Same FAR/AAC detectors and directions",
            "Same external liquidity target",
            "Same four-market semantic gate",
            "Same exact current-NAV 3% planned-loss budget",
            "Same fees, order types per selected variant, global slot and NautilusTrader accounting",
        ],
        "baseline_candidate14": {
            "daily_geometric_growth": baseline["daily_geometric_growth"],
            "nav_multiple": baseline["nav_multiple"],
            "closed_trades": baseline["closed_trades"],
            "wins": baseline["wins"],
            "losses": baseline["losses"],
            "win_rate": baseline["win_rate"],
            "active_weeks": baseline["active_weeks"],
            "payoff_ratio": baseline["payoff_ratio"],
        },
        "variants": variants,
        "success_claim": False,
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    lines = [
        "# Candidate 15 FAR execution development comparison",
        "",
        "**DEVELOPMENT REPLAY ONLY — NO SUCCESS CLAIM**",
        "",
        "| Variant | Daily geo | NAV multiple | Trades | W/L | Win rate | Active weeks | Payoff |",
        "|---|---:|---:|---:|---:|---:|---:|---:|",
        (
            f"| Candidate 14 baseline | {baseline['daily_geometric_growth']:.6%} | "
            f"{baseline['nav_multiple']:.6f} | {baseline['closed_trades']} | "
            f"{baseline['wins']}/{baseline['losses']} | {baseline['win_rate']:.2%} | "
            f"{baseline['active_weeks']} | {baseline['payoff_ratio']:.3f} |"
        ),
    ]
    for variant in VARIANTS:
        row = variants[variant]
        payoff_text = "n/a" if row["payoff_ratio"] is None else f"{row['payoff_ratio']:.3f}"
        lines.append(
            f"| {variant} | {row['daily_geometric_growth']:.6%} | {row['nav_multiple']:.6f} | "
            f"{row['closed_trades']} | {row['wins']}/{row['losses']} | {row['win_rate']:.2%} | "
            f"{row['active_weeks']} | {payoff_text} |"
        )
    lines.extend(
        [
            "",
            "The comparison changes only FAR execution after the same completed scenario confirmation. Any promoted candidate requires a new source freeze and untouched holdouts.",
        ]
    )
    args.output.with_name("RESULT.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(json.dumps(payload, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
