#!/usr/bin/env python3
"""Sequential evidence-driven Candidate 05 research orchestrator.

This is not a backtest engine.  Every experiment invokes ``candidate.py stage``;
NautilusTrader therefore remains the sole event replay, order matching, fill,
fee, position, margin, liquidation, accounting and NAV engine.  This module only
controls frozen ranges, strategy entrypoints, evidence classification and staged
promotion.
"""
from __future__ import annotations

import argparse
from dataclasses import dataclass
import json
import math
import os
from pathlib import Path
import shutil
import subprocess
import sys
from typing import Any


ROOT = Path(__file__).resolve().parent
CANDIDATE = ROOT / "candidate.py"
CONFIG = ROOT / "config.json"
STRATEGY_ENTRYPOINT = ROOT / "strategy.py"


@dataclass(frozen=True, slots=True)
class StrategySpec:
    name: str
    module: str
    class_name: str
    branch: str | None = None


@dataclass(frozen=True, slots=True)
class RangeSpec:
    name: str
    build_start: str
    build_end: str
    evaluation_start: str
    evaluation_end: str
    calendar_days: int


V26 = StrategySpec("v26", "strategy_v26", "ScenarioValidEntryStrategy")
NO_EARLY = StrategySpec(
    "v26_no_early_sponsored",
    "strategy_v26_no_early_sponsored_ablation",
    "NoEarlySponsoredParticipationStrategy",
)
V29B = StrategySpec(
    "v29b_external_displacement_fvg",
    "strategy_v29b_external_displacement_fvg",
    "ExternalDisplacementFvgStrategyV2",
    "EXTERNAL_DISPLACEMENT_FVG_RETEST",
)
V30 = StrategySpec(
    "v30_external_acceptance_retest",
    "strategy_v30_external_acceptance_retest",
    "ExternalAcceptanceFirstRetestStrategy",
    "EXTERNAL_ACCEPTANCE_FIRST_RETEST",
)
V31 = StrategySpec(
    "v31_impact_resiliency_reversal",
    "strategy_v31_impact_resiliency_reversal",
    "ImpactResiliencyReversalStrategy",
    "EXTERNAL_IMPACT_RESILIENCY_REVERSAL",
)

WEEKS = (
    RangeSpec("week-1", "2023-07-07", "2023-07-15", "2023-07-09", "2023-07-15", 7),
    RangeSpec("week-2", "2024-01-13", "2024-01-21", "2024-01-15", "2024-01-21", 7),
    RangeSpec("week-3", "2023-09-06", "2023-09-14", "2023-09-08", "2023-09-14", 7),
)
CONTINUOUS_30D = RangeSpec(
    "continuous-30d",
    "2024-02-28",
    "2024-03-30",
    "2024-03-01",
    "2024-03-30",
    30,
)
CONTINUOUS_91D = RangeSpec(
    "continuous-91d",
    "2024-02-28",
    "2024-05-30",
    "2024-03-01",
    "2024-05-30",
    91,
)


def atomic_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(
        json.dumps(value, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    temporary.replace(path)


def runtime_entrypoint(spec: StrategySpec) -> str:
    return (
        '"""Runtime entrypoint generated by master_research.py.\n\n'
        "NautilusTrader still owns replay, execution and NAV.\n"
        '"""\n'
        "from strategy_base import LiquidityResponseConfig\n"
        f"from {spec.module} import {spec.class_name} as LiquidityResponseStrategy\n"
        '__all__ = ["LiquidityResponseConfig", "LiquidityResponseStrategy"]\n'
    )


def compact_metrics(metrics: dict[str, Any]) -> dict[str, Any]:
    diagnostics = metrics.get("strategy_diagnostics", {})
    return {
        "available": True,
        "engine": metrics.get("engine"),
        "instrument": metrics.get("instrument"),
        "evaluation_start": metrics.get("evaluation_start"),
        "evaluation_end": metrics.get("evaluation_end"),
        "calendar_days": metrics.get("calendar_days"),
        "starting_nav": metrics.get("starting_nav"),
        "ending_nav": metrics.get("ending_nav"),
        "total_return": metrics.get("total_return"),
        "geometric_daily_growth": metrics.get("geometric_daily_growth"),
        "max_drawdown": metrics.get("max_drawdown"),
        "trades": metrics.get("trades"),
        "wins": metrics.get("wins"),
        "losses": metrics.get("losses"),
        "win_rate": metrics.get("win_rate"),
        "profit_factor": metrics.get("profit_factor"),
        "expectancy_usdt": metrics.get("expectancy_usdt"),
        "active_days": metrics.get("active_days"),
        "largest_winner_share": metrics.get("largest_winner_share"),
        "liquidations": metrics.get("liquidations"),
        "scenario_metrics": metrics.get("scenario_metrics", {}),
        "relevant_diagnostics": {
            key: value
            for key, value in diagnostics.items()
            if (
                key.startswith("external_")
                or key.startswith("impact_resiliency_")
                or key.startswith("early_sponsored_")
                or key in {
                    "entry_submissions",
                    "order_rejections",
                    "order_denials",
                    "max_simultaneous_entry_intents",
                    "max_open_positions_observed",
                }
            )
        },
    }


def integrity_checks(metrics: dict[str, Any]) -> dict[str, bool]:
    diagnostics = metrics.get("strategy_diagnostics", {})
    trades = int(metrics.get("trades", 0) or 0)
    gate = metrics.get("gate_checks", {})
    checks = {
        "engine_is_nautilus": metrics.get("engine") == "NautilusTrader BacktestNode",
        "positive_nav": float(metrics.get("ending_nav", 0.0) or 0.0) > 0.0,
        "no_liquidation": int(metrics.get("liquidations", 0) or 0) == 0,
        "no_order_rejections": int(diagnostics.get("order_rejections", 0) or 0) == 0,
        "no_order_denials": int(diagnostics.get("order_denials", 0) or 0) == 0,
        "single_entry_intent": int(diagnostics.get("max_simultaneous_entry_intents", 0) or 0) <= 1,
        "single_position": int(diagnostics.get("max_open_positions_observed", 0) or 0) <= 1,
        "nautilus_positions_consistent": bool(gate.get("nautilus_positions", True)),
    }
    # A completed zero-trade observation is a logical no-opportunity result, not
    # an execution-engine failure.  Orders are required only when trades exist.
    checks["nautilus_orders_consistent"] = (
        bool(gate.get("nautilus_orders", False)) if trades > 0 else True
    )
    return checks


def run_integrity(run: dict[str, Any]) -> bool:
    return bool(run.get("available")) and all(run.get("integrity_checks", {}).values())


def run_variant(
    *,
    spec: StrategySpec,
    range_spec: RangeSpec,
    output_root: Path,
    cache_root: Path,
    python: str,
) -> dict[str, Any]:
    output = output_root / spec.name / range_spec.name
    if output.exists():
        shutil.rmtree(output)
    output.mkdir(parents=True, exist_ok=True)
    cache = cache_root / range_spec.name
    cache.mkdir(parents=True, exist_ok=True)
    STRATEGY_ENTRYPOINT.write_text(runtime_entrypoint(spec), encoding="utf-8")

    command = [
        python,
        str(CANDIDATE),
        "stage",
        "--config",
        str(CONFIG),
        "--build-start",
        range_spec.build_start,
        "--build-end",
        range_spec.build_end,
        "--evaluation-start",
        range_spec.evaluation_start,
        "--evaluation-end",
        range_spec.evaluation_end,
        "--cache",
        str(cache),
        "--output",
        str(output),
    ]
    environment = os.environ.copy()
    environment["PYTHONPATH"] = str(ROOT)
    environment["PYTHONUNBUFFERED"] = "1"
    completed = subprocess.run(
        command,
        cwd=ROOT.parent.parent,
        env=environment,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    (output / "master_console.log").write_text(
        completed.stdout or "",
        encoding="utf-8",
    )
    metrics_path = output / "metrics.json"
    if completed.returncode != 0 or not metrics_path.exists():
        return {
            "available": False,
            "strategy": f"{spec.module}:{spec.class_name}",
            "range": range_spec.name,
            "return_code": completed.returncode,
            "error_log_tail": (completed.stdout or "").splitlines()[-220:],
            "classification": "IMPLEMENTATION_OR_EVIDENCE_ERROR",
        }
    try:
        metrics = json.loads(metrics_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return {
            "available": False,
            "strategy": f"{spec.module}:{spec.class_name}",
            "range": range_spec.name,
            "return_code": completed.returncode,
            "error": repr(exc),
            "classification": "IMPLEMENTATION_OR_EVIDENCE_ERROR",
        }
    result = compact_metrics(metrics)
    checks = integrity_checks(metrics)
    result.update(
        {
            "strategy": f"{spec.module}:{spec.class_name}",
            "range": range_spec.name,
            "return_code": completed.returncode,
            "integrity_checks": checks,
            "integrity_pass": all(checks.values()),
            "artifact_directory": str(output),
        },
    )
    return result


def branch_metrics(run: dict[str, Any], branch: str) -> dict[str, Any]:
    value = run.get("scenario_metrics", {}).get(branch, {})
    return {
        "trades": int(value.get("trades", 0) or 0),
        "wins": int(value.get("wins", 0) or 0),
        "net_pnl": float(value.get("net_pnl", 0.0) or 0.0),
    }


def classify_week1(
    *,
    baseline: dict[str, Any],
    candidate: dict[str, Any],
    branch: str,
) -> dict[str, Any]:
    contribution = branch_metrics(candidate, branch)
    if not run_integrity(baseline):
        classification = "IMPLEMENTATION_ERROR_BASELINE_CONTROL"
        passed = False
    elif not run_integrity(candidate):
        classification = "IMPLEMENTATION_ERROR_CANDIDATE"
        passed = False
    elif contribution["trades"] == 0:
        classification = "LOGIC_FAILURE_NO_INCREMENTAL_EXECUTABLE_OPPORTUNITY"
        passed = False
    elif contribution["net_pnl"] <= 0.0:
        classification = "LOGIC_FAILURE_NONPOSITIVE_INCREMENTAL_EXPECTANCY"
        passed = False
    elif float(candidate["geometric_daily_growth"]) <= float(baseline["geometric_daily_growth"]):
        classification = "LOGIC_FAILURE_DID_NOT_IMPROVE_CONTROL"
        passed = False
    else:
        classification = "LOGIC_SCREEN_PASSED_WEEK_1"
        passed = True
    return {
        "classification": classification,
        "passed": passed,
        "branch": contribution,
        "baseline_geometric_daily_growth": baseline.get("geometric_daily_growth"),
        "candidate_geometric_daily_growth": candidate.get("geometric_daily_growth"),
    }


def aggregate_three_weeks(
    *,
    baseline_runs: list[dict[str, Any]],
    candidate_runs: list[dict[str, Any]],
    branch: str,
) -> dict[str, Any]:
    if not all(run_integrity(run) for run in baseline_runs):
        return {"classification": "IMPLEMENTATION_ERROR_BASELINE_WEEKS", "passed": False}
    if not all(run_integrity(run) for run in candidate_runs):
        return {"classification": "IMPLEMENTATION_ERROR_CANDIDATE_WEEKS", "passed": False}
    baseline_multiple = math.prod(1.0 + float(run["total_return"]) for run in baseline_runs)
    candidate_multiple = math.prod(1.0 + float(run["total_return"]) for run in candidate_runs)
    total_days = sum(int(run["calendar_days"]) for run in candidate_runs)
    baseline_growth = baseline_multiple ** (1.0 / total_days) - 1.0
    candidate_growth = candidate_multiple ** (1.0 / total_days) - 1.0
    contribution = {"trades": 0, "wins": 0, "net_pnl": 0.0}
    for run in candidate_runs:
        item = branch_metrics(run, branch)
        for key in contribution:
            contribution[key] += item[key]
    passed = (
        contribution["trades"] > 0
        and contribution["net_pnl"] > 0.0
        and candidate_growth > baseline_growth
    )
    return {
        "classification": (
            "LOGIC_SCREEN_PASSED_THREE_WEEKS"
            if passed
            else "LOGIC_FAILURE_NOT_REPEATED_ACROSS_THREE_WEEKS"
        ),
        "passed": passed,
        "calendar_days": total_days,
        "baseline_multiple": baseline_multiple,
        "candidate_multiple": candidate_multiple,
        "baseline_geometric_daily_growth": baseline_growth,
        "candidate_geometric_daily_growth": candidate_growth,
        "branch": contribution,
    }


def btc_long_gate(run: dict[str, Any]) -> dict[str, Any]:
    if not run_integrity(run):
        return {
            "classification": "IMPLEMENTATION_OR_EVIDENCE_ERROR_91D",
            "passed": False,
        }
    checks = {
        "geometric_daily_growth": float(run.get("geometric_daily_growth", -1.0)) >= 0.01,
        "trades": int(run.get("trades", 0) or 0) >= 45,
        "active_days": int(run.get("active_days", 0) or 0) >= 30,
        "largest_winner_share": float(run.get("largest_winner_share", 1.0) or 1.0) <= 0.25,
        "max_drawdown_recoverable": float(run.get("max_drawdown", 1.0) or 1.0) < 1.0,
    }
    return {
        "classification": (
            "BTC_91D_ALPHA_GATE_PASSED"
            if all(checks.values())
            else "BTC_91D_ALPHA_GATE_FAILED"
        ),
        "passed": all(checks.values()),
        "checks": checks,
    }


def controlled_candidate_pipeline(
    *,
    spec: StrategySpec,
    baseline_weeks: list[dict[str, Any]],
    output_root: Path,
    cache_root: Path,
    python: str,
) -> dict[str, Any]:
    assert spec.branch is not None
    runs: dict[str, Any] = {}
    week1 = run_variant(
        spec=spec,
        range_spec=WEEKS[0],
        output_root=output_root,
        cache_root=cache_root,
        python=python,
    )
    runs[WEEKS[0].name] = week1
    week1_decision = classify_week1(
        baseline=baseline_weeks[0],
        candidate=week1,
        branch=spec.branch,
    )
    if not week1_decision["passed"]:
        return {
            "strategy": f"{spec.module}:{spec.class_name}",
            "branch": spec.branch,
            "classification": week1_decision["classification"],
            "implementation_error": week1_decision["classification"].startswith("IMPLEMENTATION"),
            "logic_failure": week1_decision["classification"].startswith("LOGIC_FAILURE"),
            "week1_decision": week1_decision,
            "runs": runs,
        }

    for range_spec in WEEKS[1:]:
        runs[range_spec.name] = run_variant(
            spec=spec,
            range_spec=range_spec,
            output_root=output_root,
            cache_root=cache_root,
            python=python,
        )
    three_week = aggregate_three_weeks(
        baseline_runs=baseline_weeks,
        candidate_runs=[runs[range_spec.name] for range_spec in WEEKS],
        branch=spec.branch,
    )
    if not three_week["passed"]:
        return {
            "strategy": f"{spec.module}:{spec.class_name}",
            "branch": spec.branch,
            "classification": three_week["classification"],
            "implementation_error": three_week["classification"].startswith("IMPLEMENTATION"),
            "logic_failure": three_week["classification"].startswith("LOGIC_FAILURE"),
            "week1_decision": week1_decision,
            "three_week_decision": three_week,
            "runs": runs,
        }

    run_30d = run_variant(
        spec=spec,
        range_spec=CONTINUOUS_30D,
        output_root=output_root,
        cache_root=cache_root,
        python=python,
    )
    runs[CONTINUOUS_30D.name] = run_30d
    if not run_integrity(run_30d):
        return {
            "strategy": f"{spec.module}:{spec.class_name}",
            "branch": spec.branch,
            "classification": "IMPLEMENTATION_OR_EVIDENCE_ERROR_30D",
            "implementation_error": True,
            "logic_failure": False,
            "week1_decision": week1_decision,
            "three_week_decision": three_week,
            "runs": runs,
        }
    if float(run_30d["geometric_daily_growth"]) < 0.01:
        return {
            "strategy": f"{spec.module}:{spec.class_name}",
            "branch": spec.branch,
            "classification": "LOGIC_FAILURE_BELOW_GOAL_ON_CONTINUOUS_30D",
            "implementation_error": False,
            "logic_failure": True,
            "week1_decision": week1_decision,
            "three_week_decision": three_week,
            "runs": runs,
        }

    run_91d = run_variant(
        spec=spec,
        range_spec=CONTINUOUS_91D,
        output_root=output_root,
        cache_root=cache_root,
        python=python,
    )
    runs[CONTINUOUS_91D.name] = run_91d
    long_gate = btc_long_gate(run_91d)
    return {
        "strategy": f"{spec.module}:{spec.class_name}",
        "branch": spec.branch,
        "classification": long_gate["classification"],
        "implementation_error": long_gate["classification"].startswith("IMPLEMENTATION"),
        "logic_failure": not long_gate["passed"] and not long_gate["classification"].startswith("IMPLEMENTATION"),
        "week1_decision": week1_decision,
        "three_week_decision": three_week,
        "long_gate": long_gate,
        "runs": runs,
    }


def v26_control_pipeline(
    *,
    output_root: Path,
    cache_root: Path,
    python: str,
) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    baseline_weeks = [
        run_variant(
            spec=V26,
            range_spec=range_spec,
            output_root=output_root,
            cache_root=cache_root,
            python=python,
        )
        for range_spec in WEEKS
    ]
    baseline_30d = run_variant(
        spec=V26,
        range_spec=CONTINUOUS_30D,
        output_root=output_root,
        cache_root=cache_root,
        python=python,
    )
    ablation_30d = run_variant(
        spec=NO_EARLY,
        range_spec=CONTINUOUS_30D,
        output_root=output_root,
        cache_root=cache_root,
        python=python,
    )

    valid = [run for run in (baseline_30d, ablation_30d) if run_integrity(run)]
    selected = max(valid, key=lambda run: float(run["geometric_daily_growth"])) if valid else None
    decision: dict[str, Any] = {
        "baseline_weeks": baseline_weeks,
        "baseline_30d": baseline_30d,
        "no_early_sponsored_30d": ablation_30d,
        "selected_30d": selected,
        "classification": "IMPLEMENTATION_OR_EVIDENCE_ERROR_30D" if selected is None else "SELECTED_STRONGER_VALID_30D_VARIANT",
    }
    if selected is None or float(selected["geometric_daily_growth"]) < 0.01:
        decision["promotion_91d"] = {
            "eligible": False,
            "classification": "PROMOTION_BLOCKED_BELOW_1PCT_GEOMETRIC_DAILY_GROWTH",
        }
        return baseline_weeks, decision

    selected_spec = V26 if selected["strategy"].startswith(V26.module + ":") else NO_EARLY
    long_run = run_variant(
        spec=selected_spec,
        range_spec=CONTINUOUS_91D,
        output_root=output_root,
        cache_root=cache_root,
        python=python,
    )
    long_gate = btc_long_gate(long_run)
    decision["promotion_91d"] = {
        "eligible": True,
        "selected_strategy": f"{selected_spec.module}:{selected_spec.class_name}",
        "run": long_run,
        "gate": long_gate,
    }
    return baseline_weeks, decision


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--cache", type=Path, required=True)
    parser.add_argument("--summary", type=Path, required=True)
    parser.add_argument("--python", default=sys.executable)
    args = parser.parse_args()

    output_root = args.output.resolve()
    cache_root = args.cache.resolve()
    output_root.mkdir(parents=True, exist_ok=True)
    cache_root.mkdir(parents=True, exist_ok=True)
    original_entrypoint = STRATEGY_ENTRYPOINT.read_text(encoding="utf-8")

    summary: dict[str, Any] = {
        "schema": "candidate-05-master-research-continuation-v1",
        "source_commit": os.environ.get("GITHUB_SHA"),
        "workflow_run_id": os.environ.get("GITHUB_RUN_ID"),
        "engine_contract": "Every run invokes candidate.py stage and NautilusTrader BacktestNode.",
        "risk_contract": "3% full-current-NAV planned stop-fill loss including costs; no arbitrary notional or model multiplier.",
        "fixed_ranges": [range_spec.__dict__ for range_spec in (*WEEKS, CONTINUOUS_30D, CONTINUOUS_91D)],
        "candidate_order": [V29B.name, V30.name, V31.name],
        "experiments": {},
        "winner": None,
    }
    try:
        baseline_weeks, v26_decision = v26_control_pipeline(
            output_root=output_root,
            cache_root=cache_root,
            python=args.python,
        )
        summary["experiments"]["v26_control_and_ablation"] = v26_decision
        promotion = v26_decision.get("promotion_91d", {})
        if promotion.get("eligible") and promotion.get("gate", {}).get("passed"):
            summary["winner"] = promotion["selected_strategy"]
            summary["classification"] = "BTC_91D_ALPHA_GATE_PASSED"
        elif not all(run_integrity(run) for run in baseline_weeks):
            summary["classification"] = "IMPLEMENTATION_ERROR_V26_BASELINE_WEEKS"
        else:
            # v29b is tested first.  An implementation error stops the chain;
            # v30 is a logical ablation and cannot repair an unexecuted program.
            v29b = controlled_candidate_pipeline(
                spec=V29B,
                baseline_weeks=baseline_weeks,
                output_root=output_root,
                cache_root=cache_root,
                python=args.python,
            )
            summary["experiments"][V29B.name] = v29b
            if v29b["classification"] == "BTC_91D_ALPHA_GATE_PASSED":
                summary["winner"] = v29b["strategy"]
                summary["classification"] = v29b["classification"]
            elif v29b.get("implementation_error"):
                summary["classification"] = v29b["classification"]
            else:
                v30 = controlled_candidate_pipeline(
                    spec=V30,
                    baseline_weeks=baseline_weeks,
                    output_root=output_root,
                    cache_root=cache_root,
                    python=args.python,
                )
                summary["experiments"][V30.name] = v30
                if v30["classification"] == "BTC_91D_ALPHA_GATE_PASSED":
                    summary["winner"] = v30["strategy"]
                    summary["classification"] = v30["classification"]
                elif v30.get("implementation_error"):
                    summary["classification"] = v30["classification"]
                else:
                    v31 = controlled_candidate_pipeline(
                        spec=V31,
                        baseline_weeks=baseline_weeks,
                        output_root=output_root,
                        cache_root=cache_root,
                        python=args.python,
                    )
                    summary["experiments"][V31.name] = v31
                    if v31["classification"] == "BTC_91D_ALPHA_GATE_PASSED":
                        summary["winner"] = v31["strategy"]
                    summary["classification"] = v31["classification"]

        if summary["winner"] is not None:
            summary["next_action"] = (
                "Freeze the winning BTC logic and build the real one-account four-symbol NautilusTrader competition "
                "with at most one pending entry intent or open position globally."
            )
        elif str(summary.get("classification", "")).startswith("IMPLEMENTATION"):
            summary["next_action"] = (
                "Repair the latest implementation under variable control and rerun the identical frozen range; "
                "do not interpret the candidate's market logic yet."
            )
        else:
            summary["next_action"] = (
                "Record the failed families and their useful observations, retain v26 as the active baseline, "
                "and formulate the next orthogonal alpha mechanism."
            )
        atomic_json(args.summary.resolve(), summary)
        atomic_json(output_root / "master_research_summary.json", summary)
        print(json.dumps(summary, indent=2, sort_keys=True))
    finally:
        STRATEGY_ENTRYPOINT.write_text(original_entrypoint, encoding="utf-8")


if __name__ == "__main__":
    main()
