#!/usr/bin/env python3
"""Fail-closed source materialization for Candidate 13 V9."""
from __future__ import annotations

def _replace(source: str, old: str, new: str, *, label: str, expected: int=1) -> str:
    count = source.count(old)
    if count != expected:
        raise RuntimeError(f'Candidate 13 V9 portfolio boundary drifted at {label}: expected {expected} occurrence(s), found {count}')
    return source.replace(old, new)

def materialize_quarter_hour_source(source: str) -> str:
    source = _replace(source, '        frame = frame[pd.to_numeric(frame["open_time"], errors="coerce").notna()].copy()\n        if len(frame.index) not in (1439, 1440, 1441):', '        numeric_open_time = pd.to_numeric(frame["open_time"], errors="coerce")\n        valid_open_time = numeric_open_time.notna()\n        frame = frame.loc[valid_open_time].copy()\n        frame["open_time"] = numeric_open_time.loc[valid_open_time].astype("int64")\n        # candidate-13-v9-strict-open-time: normalize mixed header/integer archives before sort.\n        if len(frame.index) not in (1439, 1440, 1441):', label='strict-open-time')
    source = _replace(source, 'from session_engine import RegionalHandoffAuctionEngine\n\nfrom smc_ict_4.event_log import EventLogError, write_events', 'from session_engine import RegionalHandoffAuctionEngine\nfrom quarter_hour_common_flow import (\n    QH_LOGIC_KEY,\n    QuarterHourCommonFlowEngine,\n)\n\nfrom smc_ict_4.event_log import EventLogError, write_events', label='imports')
    source = _replace(source, '    logics: dict[str, RegionalHandoffAuctionEngine],', '    logics: dict[str, Any],', label='metrics-logic-type')
    source = _replace(source, '        "scenario_counts": {\n            scenario: sum(plan["scenario"] == scenario for plan in plans)\n            for scenario in ("FAR", "AAC")\n        },\n        "symbol_counts": {', '        "scenario_counts": {\n            scenario: sum(plan["scenario"] == scenario for plan in plans)\n            for scenario in sorted({str(plan.get("scenario", "UNKNOWN")) for plan in plans})\n        },\n        "module_counts": {\n            module: sum(plan.get("module", "SCDAM_CORE") == module for plan in plans)\n            for module in sorted({str(plan.get("module", "SCDAM_CORE")) for plan in plans})\n        },\n        "symbol_counts": {', label='dynamic-module-metrics')
    source = _replace(source, '            self.logic = {\n                symbol: RegionalHandoffAuctionEngine(logic_config, str(instruments[symbol].id))\n                for symbol in SYMBOLS\n            }\n            self.sizer = RiskSizer(logic_config.risk_fraction)', '            self.logic = {\n                symbol: RegionalHandoffAuctionEngine(logic_config, str(instruments[symbol].id))\n                for symbol in SYMBOLS\n            }\n            self.quarter_hour_key = QH_LOGIC_KEY\n            self.logic[self.quarter_hour_key] = QuarterHourCommonFlowEngine(logic_config)\n            self.sizer = RiskSizer(logic_config.risk_fraction)', label='strategy-quarter-hour-engine')
    source = _replace(source, '            self.event_cursor = {symbol: 0 for symbol in SYMBOLS}', '            self.event_cursor = {logic_key: 0 for logic_key in self.logic}', label='event-cursors')
    source = _replace(source, '        def _capture_events(self, symbol: str) -> None:\n            engine = self.logic[symbol]\n            cursor = self.event_cursor[symbol]\n            if cursor < len(engine.events):\n                self.events.extend(engine.events[cursor:])\n                self.event_cursor[symbol] = len(engine.events)\n', '        def _capture_events(self, logic_key: str) -> None:\n            engine = self.logic[logic_key]\n            cursor = self.event_cursor[logic_key]\n            if cursor < len(engine.events):\n                self.events.extend(engine.events[cursor:])\n                self.event_cursor[logic_key] = len(engine.events)\n', label='event-capture-routing')
    source = _replace(source, '        def _all_flat(self) -> bool:\n            return all(self.portfolio.is_flat(instrument_id) for instrument_id in self.config.instrument_ids)\n\n        def _account_values(self) -> tuple[Decimal, Decimal]:', '        def _all_flat(self) -> bool:\n            return all(self.portfolio.is_flat(instrument_id) for instrument_id in self.config.instrument_ids)\n\n        @staticmethod\n        def _logic_key_for_plan(plan: Any | None, symbol: str) -> str:\n            if plan is None:\n                return symbol\n            details = getattr(plan, "details", {})\n            return str(details.get("_logic_key", symbol))\n\n        def _logic_for_plan(self, plan: Any, symbol: str) -> Any:\n            return self.logic[self._logic_key_for_plan(plan, symbol)]\n\n        def _account_values(self) -> tuple[Decimal, Decimal]:', label='plan-origin-routing')
    source = _replace(source, 'self.logic[self.active_symbol]', 'self._logic_for_plan(self.active_plan, self.active_symbol)', label='active-lifecycle-routing', expected=3)
    source = _replace(source, 'self._capture_events(self.active_symbol)', 'self._capture_events(self._logic_key_for_plan(self.active_plan, self.active_symbol))', label='active-event-routing', expected=3)
    source = _replace(source, 'self.logic[symbol].mark_rejected(', 'self._logic_for_plan(plan, symbol).mark_rejected(', label='symbol-rejection-routing', expected=5)
    source = _replace(source, 'self.logic[symbol].mark_submitted(', 'self._logic_for_plan(plan, symbol).mark_submitted(', label='submission-routing')
    source = _replace(source, 'self._capture_events(symbol)', 'self._capture_events(self._logic_key_for_plan(plan, symbol))', label='symbol-event-routing', expected=7)
    source = _replace(source, 'self.logic[rejected.symbol].mark_rejected(', 'self._logic_for_plan(plan, rejected.symbol).mark_rejected(', label='arbitration-rejection-routing', expected=2)
    source = _replace(source, 'self._capture_events(rejected.symbol)', 'self._capture_events(self._logic_key_for_plan(plan, rejected.symbol))', label='arbitration-event-routing', expected=2)
    source = _replace(source, '            self.plans.append({\n                "symbol": symbol,\n                "scenario_id": plan.scenario_id,', '            self.plans.append({\n                "symbol": symbol,\n                "module": str(plan.details.get("module", "SCDAM_CORE")),\n                "scenario_id": plan.scenario_id,', label='plan-module-evidence')
    source = _replace(source, '                plans.append((plan, candidate))\n\n            if not plans:\n                return', '                plans.append((plan, candidate))\n\n            for qh_symbol, qh_plan in self.logic[self.quarter_hour_key].on_batch(\n                ts_ns,\n                self.buffer,\n            ):\n                self._capture_events(self.quarter_hour_key)\n                if ts_ns < self.config.evaluation_start_ns:\n                    self.logic[self.quarter_hour_key].mark_rejected(\n                        qh_plan,\n                        ts_ns,\n                        "OUTSIDE_EVALUATION_WINDOW",\n                    )\n                    self._capture_events(self.quarter_hour_key)\n                    continue\n                qh_candidate = Candidate(\n                    symbol=qh_symbol,\n                    scenario_id=qh_plan.scenario_id,\n                    observed_ts_ns=qh_plan.observed_ts_ns,\n                    net_structural_r=Decimal(str(qh_plan.net_r)),\n                    expected_entry=Decimal(str(qh_plan.expected_entry)),\n                    expected_loss_per_unit=Decimal(str(qh_plan.loss_per_unit)),\n                )\n                plans.append((qh_plan, qh_candidate))\n            self._capture_events(self.quarter_hour_key)\n\n            if not plans:\n                return', label='quarter-hour-plan-generation')
    required = ('candidate-13-v9-strict-open-time', 'QuarterHourCommonFlowEngine(logic_config)', 'on_batch(\n                ts_ns,\n                self.buffer,', 'plans.append((qh_plan, qh_candidate))')
    missing = [token for token in required if source.count(token) != 1]
    if missing:
        raise RuntimeError(f'Candidate 13 V9 routes not materialized exactly once: {missing}')
    return source
