#!/usr/bin/env python3
"""Stable Candidate 13 entry point and executable production-boundary helpers.

The frozen implementation remains in ``run_leadership_scdam``.  This module
re-exports it under the repository's conventional ``run.py`` entry point and
makes the Nautilus GTD/report boundary directly testable without duplicating
strategy logic.
"""
from __future__ import annotations

from datetime import datetime, timedelta, timezone
from typing import Any

from nautilus_trader.model.enums import OrderType, TimeInForce

from run_leadership_scdam import main, run


def build_gtd_parent(order_factory: Any, plan: Any, **kwargs: Any) -> Any:
    """Build the same timezone-aware passive GTD parent contract as the runner."""
    return order_factory.bracket(
        **kwargs,
        entry_order_type=OrderType.LIMIT,
        time_in_force=TimeInForce.GTD,
        expire_time=datetime.fromtimestamp(
            plan.expire_ts_ns / 1_000_000_000,
            tz=timezone.utc,
        ) + timedelta(microseconds=1),
    )


def fills_report(engine: Any) -> Any:
    """Return fills generated by NautilusTrader, never by a local simulator."""
    return engine.trader.generate_order_fills_report()


if __name__ == "__main__":
    raise SystemExit(main())
